# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Run Full Audit
on:
  workflow_dispatch:

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.EDFI_BUILD_AGENT_PAT }}

permissions:
  actions: read
  contents: read
  pull-requests: read
  security-events: read

jobs:
  audit:
    name: Audit Ed-Fi Organizations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: edfi-repo-auditor

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Audit Ed-Fi-Alliance-OSS
        run: poetry run python edfi_repo_auditor -p ${{ env.PERSONAL_ACCESS_TOKEN }} -s -o Ed-Fi-Alliance-OSS  -f Ed-Fi-Alliance-OSS

      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: audit-result-Ed-Fi-Alliance-OSS
          path: ./edfi-repo-auditor/reports/*
          if-no-files-found: error
          retention-days: 10
