# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Test Metrics
on:
  pull_request:
    paths:
      - 'metrics/**'
  push:
    paths:
      - 'metrics/**'
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: metrics
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.12
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry env use "3.12" && poetry install

      - name: Lint
        run: poetry run flake8

      - name: Type Check
        if: always()
        run: poetry run mypy . --junit-xml mypy-junit.xml

      - name: Unit Tests
        if: always()
        run: poetry run pytest --junitxml=pytest-junit.xml
